name = input("Ваше имя: ")
surname = input("Фамилия: ")
age = input("Возраст: ")
print("Ваше имя: {}, Фамилия: {}, Возраст: {} лет".format(name, surname, age))
print(f"Ваше имя: {name}, Фамилия: {surname}, Возраст: {age} лет")